export const textdata = [{
    "en": {
        "home": "Home",
        "about": "About",
        "today": "Today the solar park produced enough energy to",
        "temp": "Temperature",
        "energy": "Energy Production",
        "sun": "Daily Sun Hours",
        "accuracy": "Precision",
        "produce": "Produce ",
        "coffe": " pots of coffee ",
        "microwave": "Power a microwave oven for ",
        "kettle": "Power a kettle for ",
        "hours": " hours",
        "tesla": "Drive a Tesla Model S for ",
        "km": " km",
        "household": "Power a household for ",
        "days": " days",
        "hourly": "Hourly",
        "daily": "Daily",
        "monthly": "Monthly",
        "january": "January",
        "february": "February",
        "march": "March",
        "april": "April",
        "may": "May",
        "june": "June",
        "july": "July",
        "august": "August",
        "september": "September",
        "october": "October",
        "november": "November",
        "december": "December",
        "hydrogen": "Hydrogen",
        "battery": "Battery",
        "electricalGrid": "Electrical Grid"
    },
    "sv": {
        "home": "Hem",
        "about": "Om",
        "today": "Idag producerade solparken tillräckligt med energi för att",
        "temp": "Temperatur",
        "energy": "Energi Tillverkning",
        "sun": "Dagliga Soltimmar",
        "accuracy": "Precision",
        "produce": "Producera ",
        "coffe": " kannor kaffe",
        "microwave": "Driva en mikrovågsugn i ",
        "kettle": "Driva en vattenkokare i ",
        "hours": " timmar",
        "tesla": "Köra en Tesla Model S i ",
        "km": " km",
        "household": "Driva ett hushåll i ",
        "days": " dagar",
        "hourly": "Timvis",
        "daily": "Dagligen",
        "monthly": "Månatligen",
        "january": "Januari",
        "february": "Februari",
        "march": "Mars",
        "april": "April",
        "may": "Maj",
        "june": "Juni",
        "july": "Juli",
        "august": "Augusti",
        "september": "September",
        "october": "Oktober",
        "november": "November",
        "december": "December",
        "hydrogen": "Vätgas",
        "battery": "Batteri",
        "electricalGrid": "Elnät"
    },
    "fi": {
        "home": "Koti",
        "about": "Tietoa",
        "today": "Tänään aurinkopuisto tuotti tarpeeksi energiaa",
        "temp": "Lämpötila",
        "energy": "Energiantuotanto",
        "sun": "Päivittäiset auringon tunnit",
        "accuracy": "Tarkkuus",
        "produce": "Tuottaa ",
        "coffe": " kahvipannua ",
        "microwave": "Käyttää mikroaaltouunia ",
        "kettle": "Käyttää vedenkeitintä ",
        "hours": " tuntia",
        "tesla": "Ajaa Tesla Model S:ää ",
        "km": " km",
        "household": "Virtaa kotitalouteen ",
        "days": " päivää",
        "hourly": "Tunneittain",
        "daily": "Päivittäin",
        "monthly": "Kuukausittain",
        "january": "Tammikuu",
        "february": "Helmikuu",
        "march": "Maaliskuu",
        "april": "Huhtikuu",
        "may": "Toukokuu",
        "june": "Kesäkuu",
        "july": "Heinäkuu",
        "august": "Elokuu",
        "september": "Syyskuu",
        "october": "Lokakuu",
        "november": "Marraskuu",
        "december": "Joulukuu",
        "hydrogen": "Vety",
        "battery": "Akku",
        "electricalGrid": "Sähköverkko"
    }
}]
